-- Seed: AI Visibility Tools Directory
-- Run after migration 007_ai_tools.sql

INSERT INTO tools (name, slug, tagline, description, website_url, domain, category, dimensions, use_cases, pricing_model, price_from, gss_rating, pros, cons, best_for, meta_title, meta_description, is_featured, sort_order, status, published_at) VALUES

-- ============================================================
-- CONTENT TOOLS
-- ============================================================

(
  'Surfer SEO',
  'surfer-seo',
  'AI-powered content optimisation that helps you rank and get cited.',
  'Surfer analyses top-ranking content and gives you a real-time content score as you write. Its AI outline generator and NLP-driven keyword suggestions help structure articles in the way AI platforms prefer — clear headings, comprehensive coverage, and entity-rich language. The Content Editor is particularly useful for ensuring your pages cover the topics AI models associate with your target queries.',
  'https://surferseo.com',
  'surferseo.com',
  'content',
  ARRAY['content', 'citation'],
  ARRAY['content optimisation', 'keyword research', 'content briefs', 'NLP analysis'],
  'paid',
  '£69/mo',
  4,
  ARRAY['Real-time content scoring', 'NLP-driven keyword suggestions', 'AI outline generator', 'SERP analyser built in', 'Strong integration with Google Docs and WordPress'],
  ARRAY['Can feel prescriptive if followed blindly', 'Higher price point for solo operators', 'AI writing feature is average'],
  'B2B content teams who publish weekly and want data-backed structure.',
  'Surfer SEO Review — AI Visibility Tool | GTM Signal Studio',
  'Surfer SEO review: how it helps structure content for AI citation. Tested across all four AI visibility dimensions by GTM Signal Studio.',
  true,
  10,
  'published',
  now()
),

(
  'Clearscope',
  'clearscope',
  'Enterprise content optimisation for comprehensive topic coverage.',
  'Clearscope focuses on content comprehensiveness — ensuring your articles cover every subtopic and entity that search engines and AI models expect. Its grading system (A++ to F) gives writers a clear target. Where Clearscope excels for AI visibility is in its emphasis on semantic completeness. AI platforms prefer citing sources that demonstrate authoritative, thorough coverage of a topic rather than thin keyword-stuffed pages.',
  'https://www.clearscope.io',
  'clearscope.io',
  'content',
  ARRAY['content', 'entity'],
  ARRAY['content optimisation', 'topic coverage', 'editorial workflows'],
  'paid',
  '£170/mo',
  4,
  ARRAY['Excellent content grading system', 'Strong focus on semantic completeness', 'Clean, distraction-free interface', 'Good for editorial teams with multiple writers'],
  ARRAY['Expensive for small teams', 'No free tier or trial', 'Fewer integrations than Surfer'],
  'Enterprise marketing teams with dedicated content operations.',
  'Clearscope Review — AI Visibility Tool | GTM Signal Studio',
  'Clearscope review: how semantic completeness drives AI citation. Tested by GTM Signal Studio across all four visibility dimensions.',
  false,
  20,
  'published',
  now()
),

(
  'Frase',
  'frase',
  'AI content briefs and answer-engine optimisation in one tool.',
  'Frase was built for the answer-engine era. It analyses "People Also Ask" boxes, generates content briefs from SERP data, and helps you write content structured around questions — exactly the format AI platforms prefer when selecting sources to cite. The AI writing assistant is decent for first drafts, but the real value is in the research and brief generation. Frase helps you identify the questions your ICP is asking and structure content to answer them definitively.',
  'https://www.frase.io',
  'frase.io',
  'content',
  ARRAY['content', 'citation'],
  ARRAY['content briefs', 'answer optimisation', 'question research', 'AI writing'],
  'freemium',
  '£12/mo',
  4,
  ARRAY['Excellent question research from PAA data', 'Very affordable entry point', 'Content brief generation is fast', 'Good for answer-engine optimisation'],
  ARRAY['AI writing quality is hit or miss', 'UI can feel cluttered', 'Smaller keyword database than competitors'],
  'Solo marketers and small teams optimising for AI answer engines on a budget.',
  'Frase Review — AI Visibility Tool | GTM Signal Studio',
  'Frase review: question research and answer-engine optimisation. How it helps you get cited by AI platforms.',
  true,
  30,
  'published',
  now()
),

(
  'MarketMuse',
  'marketmuse',
  'AI-driven content strategy and topic authority planning.',
  'MarketMuse takes a different approach — instead of optimising individual pages, it maps your entire content ecosystem against topic authority. Its Content Inventory feature shows where you have topical gaps, and its Compete application reveals how your coverage compares to competitors. For AI visibility, MarketMuse helps you build the kind of comprehensive topical authority that AI models use to determine which sources to cite. If an AI platform needs to recommend an expert on a topic, it favours sites with deep, interconnected coverage.',
  'https://www.marketmuse.com',
  'marketmuse.com',
  'content',
  ARRAY['content', 'entity', 'citation'],
  ARRAY['content strategy', 'topic authority', 'content gap analysis', 'competitive analysis'],
  'freemium',
  '£0 (limited)',
  3,
  ARRAY['Unique topic authority modelling', 'Content gap analysis is excellent', 'Helps build systematic topical coverage', 'Free tier available for testing'],
  ARRAY['Steep learning curve', 'Paid plans are expensive', 'Can overwhelm small teams with data', 'Slower to show ROI than page-level tools'],
  'Content strategists planning long-term topical authority, not just individual posts.',
  'MarketMuse Review — AI Visibility Tool | GTM Signal Studio',
  'MarketMuse review: building topical authority for AI citation. Content strategy at the ecosystem level.',
  false,
  40,
  'published',
  now()
),

-- ============================================================
-- ENTITY / SCHEMA TOOLS
-- ============================================================

(
  'WordLift',
  'wordlift',
  'Entity-based SEO and knowledge graph builder for your website.',
  'WordLift is the most AI-visibility-focused tool on this list. It builds a knowledge graph from your content, adds structured data automatically, and connects your entities to Wikidata and other knowledge bases. This is exactly what AI platforms need — clear entity definitions, relationships, and structured data that machines can parse. WordLift essentially makes your content machine-readable in the way AI models prefer. If you are serious about entity recognition as a dimension of AI visibility, this is the tool to evaluate first.',
  'https://wordlift.io',
  'wordlift.io',
  'schema',
  ARRAY['entity', 'technical', 'citation'],
  ARRAY['knowledge graph', 'schema markup', 'entity SEO', 'structured data'],
  'paid',
  '£49/mo',
  5,
  ARRAY['Builds a proper knowledge graph from your content', 'Automatic schema markup generation', 'Connects entities to Wikidata', 'Purpose-built for AI visibility', 'WordPress plugin available'],
  ARRAY['Requires ongoing content to build the graph', 'Setup takes time to configure properly', 'WordPress-centric (limited CMS support)'],
  'B2B companies serious about entity recognition and knowledge graph SEO.',
  'WordLift Review — AI Visibility Tool | GTM Signal Studio',
  'WordLift review: knowledge graph builder for AI visibility. The most entity-focused tool we have tested.',
  true,
  50,
  'published',
  now()
),

(
  'Schema App',
  'schema-app',
  'Enterprise schema markup management and knowledge graph platform.',
  'Schema App goes beyond basic schema generators. It provides a full schema markup management platform with a visual editor, automated deployment, and — critically — a knowledge graph that connects your structured data into a coherent entity model. For larger sites with hundreds of pages, managing schema at scale is essential for AI visibility. Schema App makes this manageable without requiring developers for every change.',
  'https://www.schemaapp.com',
  'schemaapp.com',
  'schema',
  ARRAY['entity', 'technical'],
  ARRAY['schema markup', 'structured data', 'knowledge graph', 'enterprise SEO'],
  'enterprise',
  'Custom pricing',
  4,
  ARRAY['Visual schema editor', 'Automated deployment across pages', 'Enterprise-scale schema management', 'Knowledge graph builder', 'Good onboarding support'],
  ARRAY['Enterprise pricing only', 'Overkill for small sites', 'Requires schema knowledge to get full value'],
  'Enterprise sites with 100+ pages that need schema markup at scale.',
  'Schema App Review — AI Visibility Tool | GTM Signal Studio',
  'Schema App review: enterprise schema markup management for AI visibility. Knowledge graph at scale.',
  false,
  60,
  'published',
  now()
),

(
  'InLinks',
  'inlinks',
  'Entity-based internal linking and content optimisation.',
  'InLinks analyses your content through an entity lens, identifies the topics and entities on each page, and automates internal linking based on entity relationships. Internal linking is one of the most overlooked aspects of AI visibility — it helps AI platforms understand the relationships between your content and which pages are most authoritative on a given topic. InLinks also generates schema markup and provides content briefs based on entity gaps.',
  'https://inlinks.com',
  'inlinks.com',
  'schema',
  ARRAY['entity', 'content', 'technical'],
  ARRAY['internal linking', 'entity optimisation', 'schema markup', 'content briefs'],
  'paid',
  '£25/mo',
  4,
  ARRAY['Automated entity-based internal linking', 'Affordable pricing', 'Schema markup generation included', 'Entity gap analysis', 'Unique approach to content structure'],
  ARRAY['Smaller company — less support resources', 'UI is functional but not polished', 'Limited integrations'],
  'Content-heavy sites that need better internal linking and entity structure.',
  'InLinks Review — AI Visibility Tool | GTM Signal Studio',
  'InLinks review: entity-based internal linking for AI visibility. Automated topic connections and schema markup.',
  true,
  70,
  'published',
  now()
),

-- ============================================================
-- RESEARCH / MONITORING TOOLS
-- ============================================================

(
  'SparkToro',
  'sparktoro',
  'Audience intelligence — find where your ICP pays attention.',
  'SparkToro is not a traditional SEO tool, but it is essential for AI visibility strategy. It shows you where your target audience spends time online — which podcasts they listen to, which publications they read, which social accounts they follow. This intelligence is critical for citation strategy. If you know which sources AI platforms already cite for your topics, you can pursue mentions, guest posts, and partnerships with those sources. SparkToro helps you find the citation sources that matter.',
  'https://sparktoro.com',
  'sparktoro.com',
  'research',
  ARRAY['citation'],
  ARRAY['audience research', 'citation strategy', 'competitive intelligence', 'influencer discovery'],
  'freemium',
  '£0 (5 searches/mo)',
  4,
  ARRAY['Unique audience intelligence data', 'Free tier is genuinely useful', 'Excellent for citation source discovery', 'Simple, clean interface', 'Founded by Rand Fishkin — credible'],
  ARRAY['Limited searches on free plan', 'Data can be thin for niche B2B verticals', 'No direct AI visibility tracking'],
  'Marketers building a citation strategy who need to find the right sources to be mentioned by.',
  'SparkToro Review — AI Visibility Tool | GTM Signal Studio',
  'SparkToro review: audience intelligence for AI citation strategy. Find where your ICP pays attention.',
  true,
  80,
  'published',
  now()
),

(
  'Semrush',
  'semrush',
  'All-in-one SEO platform with emerging AI visibility features.',
  'Semrush is the Swiss Army knife of SEO. While it was not built specifically for AI visibility, several features are directly relevant: Position Tracking now monitors AI Overview appearances, the Content Template tool helps structure pages for featured snippets (which correlate with AI citations), and the backlink database helps you understand your citation authority. Semrush recently added AI-specific tracking features, making it increasingly useful for monitoring how your brand appears in AI-generated responses.',
  'https://www.semrush.com',
  'semrush.com',
  'monitoring',
  ARRAY['citation', 'content', 'technical'],
  ARRAY['SEO monitoring', 'AI overview tracking', 'backlink analysis', 'content templates', 'technical audits'],
  'paid',
  '£100/mo',
  4,
  ARRAY['Comprehensive SEO toolkit', 'AI Overview tracking in Position Tracking', 'Massive keyword and backlink databases', 'Content template for structure', 'Regular feature updates'],
  ARRAY['Expensive for the full suite', 'Can be overwhelming — too many features', 'AI visibility features still maturing', 'Per-seat pricing adds up'],
  'Marketing teams that need a full SEO platform and want to add AI visibility tracking.',
  'Semrush Review — AI Visibility Tool | GTM Signal Studio',
  'Semrush review: all-in-one SEO with AI visibility tracking. How to use Position Tracking for AI Overviews.',
  false,
  90,
  'published',
  now()
),

(
  'Ahrefs',
  'ahrefs',
  'Backlink intelligence and content exploration for citation authority.',
  'Ahrefs has the best backlink database in the industry, and backlinks remain a strong signal for AI citation. If authoritative sites link to your content, AI platforms are more likely to cite you. Ahrefs Content Explorer helps you find content that gets cited — showing what gets links, social shares, and organic traffic. Their Site Audit tool catches technical issues that could prevent AI crawlers from properly indexing your content.',
  'https://ahrefs.com',
  'ahrefs.com',
  'monitoring',
  ARRAY['citation', 'technical'],
  ARRAY['backlink analysis', 'content exploration', 'technical audits', 'keyword research', 'rank tracking'],
  'paid',
  '£79/mo',
  4,
  ARRAY['Best backlink database available', 'Content Explorer for citation research', 'Excellent Site Audit tool', 'Clean, intuitive interface', 'Free webmaster tools tier'],
  ARRAY['No dedicated AI visibility features yet', 'Expensive for full access', 'Limited to SEO — no content optimisation'],
  'SEO-focused teams who need deep backlink and citation authority data.',
  'Ahrefs Review — AI Visibility Tool | GTM Signal Studio',
  'Ahrefs review: backlink intelligence for AI citation authority. How backlink signals drive AI visibility.',
  false,
  100,
  'published',
  now()
),

-- ============================================================
-- TECHNICAL TOOLS
-- ============================================================

(
  'Screaming Frog',
  'screaming-frog',
  'Website crawler that finds the technical issues blocking AI visibility.',
  'Screaming Frog is the industry-standard website crawler. It finds broken links, missing schema markup, duplicate content, thin pages, redirect chains, and every other technical issue that could prevent AI platforms from properly crawling and understanding your site. For AI visibility specifically, use it to audit your schema markup coverage, check that your content is crawlable, and ensure your site structure makes topical relationships clear. The custom extraction feature lets you check for specific structured data patterns across your entire site.',
  'https://www.screamingfrog.co.uk/seo-spider/',
  'screamingfrog.co.uk',
  'technical',
  ARRAY['technical'],
  ARRAY['technical audits', 'schema validation', 'crawl analysis', 'site structure', 'redirect mapping'],
  'freemium',
  '£149/yr',
  5,
  ARRAY['Industry-standard crawler', 'Custom extraction for schema audits', 'Extremely thorough technical analysis', 'One-time annual cost (not monthly)', 'Works locally — no data leaves your machine'],
  ARRAY['Desktop app — no cloud dashboard', 'Learning curve for non-technical users', 'Large sites need decent RAM', 'UI looks dated'],
  'Anyone doing a technical AI visibility audit. Essential tool.',
  'Screaming Frog Review — AI Visibility Tool | GTM Signal Studio',
  'Screaming Frog review: the essential technical crawler for AI visibility audits. Schema, structure, and crawlability.',
  true,
  110,
  'published',
  now()
),

(
  'Sitebulb',
  'sitebulb',
  'Visual website auditor with prioritised, actionable recommendations.',
  'Sitebulb is Screaming Frog for people who want clearer answers. Instead of raw data, it gives you prioritised recommendations with severity scores and visual site maps. For AI visibility, Sitebulb is excellent at identifying structural issues — orphan pages, poor internal linking, thin content clusters — that make it harder for AI platforms to understand your topical authority. The structured data audit is particularly well-presented, showing exactly which pages have markup and which do not.',
  'https://sitebulb.com',
  'sitebulb.com',
  'technical',
  ARRAY['technical', 'content'],
  ARRAY['technical audits', 'site structure visualisation', 'schema audits', 'prioritised recommendations'],
  'paid',
  '£11/mo',
  4,
  ARRAY['Beautiful visual reports', 'Prioritised recommendations (not just raw data)', 'Excellent structured data audit', 'Affordable pricing', 'Great for presenting to stakeholders'],
  ARRAY['Desktop app only', 'Slower crawl speed than Screaming Frog', 'Fewer advanced features for power users'],
  'Marketers who need to present technical findings to non-technical stakeholders.',
  'Sitebulb Review — AI Visibility Tool | GTM Signal Studio',
  'Sitebulb review: visual website auditor for AI visibility. Prioritised recommendations for technical fixes.',
  false,
  120,
  'published',
  now()
),

(
  'Merkle Schema Markup Generator',
  'merkle-schema-generator',
  'Free schema markup generator for common structured data types.',
  'Merkle''s Schema Markup Generator is a free tool that creates JSON-LD schema markup for common types: Organization, Article, FAQ, HowTo, Product, and more. While it does not manage schema at scale, it is the fastest way to generate correct structured data for individual pages. For AI visibility, structured data is foundational — it helps AI platforms understand what your content is about, who wrote it, and how it relates to known entities. This tool removes the barrier of writing JSON-LD by hand.',
  'https://technicalseo.com/tools/schema-markup-generator/',
  'technicalseo.com',
  'schema',
  ARRAY['entity', 'technical'],
  ARRAY['schema markup', 'structured data', 'JSON-LD generation'],
  'free',
  'Free',
  3,
  ARRAY['Completely free', 'Supports many schema types', 'Clean, simple interface', 'Generates valid JSON-LD', 'No account required'],
  ARRAY['Manual process — one page at a time', 'No deployment or management features', 'No validation against live pages', 'Basic — no knowledge graph capabilities'],
  'Anyone who needs quick, correct schema markup without paying for a platform.',
  'Merkle Schema Generator Review — AI Visibility Tool | GTM Signal Studio',
  'Merkle Schema Markup Generator: free JSON-LD structured data for AI visibility. Quick schema generation.',
  false,
  130,
  'published',
  now()
),

-- ============================================================
-- AI-SPECIFIC MONITORING
-- ============================================================

(
  'Otterly.AI',
  'otterly-ai',
  'Track your brand mentions across AI search engines.',
  'Otterly.AI is built specifically for the AI visibility era. It monitors how your brand appears in ChatGPT, Perplexity, Google AI Overviews, and other AI platforms. You set up tracking queries and it shows you whether you are being cited, how your visibility changes over time, and which competitors are appearing instead. This is the closest thing to rank tracking for AI search. For B2B companies trying to measure and improve their AI visibility, Otterly provides the data you cannot get from traditional SEO tools.',
  'https://www.otterly.ai',
  'otterly.ai',
  'monitoring',
  ARRAY['citation', 'entity'],
  ARRAY['AI citation tracking', 'brand monitoring', 'competitor tracking', 'AI search analytics'],
  'freemium',
  '£0 (limited)',
  5,
  ARRAY['Purpose-built for AI visibility tracking', 'Monitors ChatGPT, Perplexity, Google AI', 'Competitor citation comparison', 'Trend tracking over time', 'Free tier to test'],
  ARRAY['Still early — features evolving quickly', 'Limited query volume on free plan', 'Newer company — smaller support team'],
  'Any B2B company that wants to measure their AI visibility and track progress.',
  'Otterly.AI Review — AI Visibility Tool | GTM Signal Studio',
  'Otterly.AI review: track your brand across AI search engines. Purpose-built AI citation monitoring.',
  true,
  5,
  'published',
  now()
),

(
  'Peec AI',
  'peec-ai',
  'AI search analytics — understand how AI platforms see your brand.',
  'Peec AI analyses your brand presence across AI-generated search results. It shows which queries trigger AI citations of your content, tracks your visibility share versus competitors, and identifies gaps where you should be appearing but are not. The tool provides actionable recommendations for improving your AI citation rate. For teams already investing in content and SEO, Peec adds the AI visibility layer that traditional tools miss.',
  'https://www.peec.ai',
  'peec.ai',
  'monitoring',
  ARRAY['citation', 'entity', 'content'],
  ARRAY['AI search analytics', 'citation tracking', 'visibility share', 'competitor analysis'],
  'paid',
  'Custom pricing',
  4,
  ARRAY['Deep AI search analytics', 'Visibility share metrics', 'Actionable improvement recommendations', 'Multi-platform coverage'],
  ARRAY['Custom pricing — no self-serve', 'Newer tool — still building features', 'Requires sales conversation to start'],
  'Marketing teams with budget who want detailed AI search analytics beyond basic tracking.',
  'Peec AI Review — AI Visibility Tool | GTM Signal Studio',
  'Peec AI review: AI search analytics for brand visibility. Understand how AI platforms see your content.',
  false,
  15,
  'published',
  now()
);
